
import { ICategoryLabels } from './categoryId.interface';
export const CategoryLabelData: ICategoryLabels =
{
  Class: 1,
  Section: 2,
  Subject: 3,
  Leave_Type: 4,
  Upload_Type: 5,
  Station: 6,
  Cast: 7,
  Allowances: 8,
  Deducations: 9,
  Bank: 10,
  Category: 11,
  Occupation: 12,
  Document: 13,
  Fees: 14,
  Examination: 15,
  Rack: 16,
  City: 17,
  Expense: 18,
  Department: 19,
  Post: 20,
  Machine: 21,
  Item_Type: 22,
  Unit_Type: 23,
  Photo_Gallery: 24,
  Period: 25,
  Bus_Master: 26,
  Chapter: 27,
  Book_Master: 28,
  Country_Name: 29,
  Income_Type: 30,
  Paper: 31,
  Religion: 32,
  Complaint: 33,
  Conveyance_Fees: 34,
  Route: 35,
  Video_Gallery: 36,
  Downloads: 37,
  Qualification: 38,
  House: 39,
  Addmission_Type: 40,
  Result_System: 41,
  Events: 42,
  Exam_Patterns: 43,
  Exam_Type: 44,
};
